### ISSUE TITLE
Comments for HW Lesson3 

### ISSUE THREAD

**Issue by alexanderpavlovets** [StartITProtractorJS/5-startit-movie-finder-ssos1#3]
it('should have "raiting" pointer', async function(){
        let raitingPointer = $$('.label-success').first();
            await browser.get('/');
            //await expect(raitingPointer.isDisplayed()).toBe(True);
    });

- Commented expect makes test always have status "passed" 
- booleans in JS are written as lowercase = true/false (not True)
- test isn't compiles, because different types inside expect(Promise) and toBe(boolean). Have to be like: 
expect(await .... await your Promise).toBe(expected result)
___

```let movieCardTitles = $$('movie-card').$$('a');```
Just an advice: you can combine such selector $$('movie-card a')
reference:  https://www.w3schools.com/cssref/css_selectors.asp
___
    it('should open "Upcoming movies" section', async function() {
        let upcomingMovies = $('[routerlink="/upcoming"]');
            await browser.get('/');
            await upcomingMovies.click();
            let upcomingMoviesTitle =  await upcomingMovies.getText();
         expect(upcomingMoviesTitle).toEqual('Upcoming Movies')
    })

This test is not checking that "Upcoming movies" section is opened. You just take a text from "Upcoming movies" title and check, that it is equal to "Upcoming movies". 
Test should check, that after click on "Upcoming movies" appropriate page is opened. 

All test in "navigation" suite have the same behavior. 
___
    it('results (all of them) should contain search request', async function(){
        let movieCardTitles = $$('movie-card').$$('a');
        let searchField = $('[name="searchStr"]');
        let goButton = $('.input-group-btn button');
        let searchResultGroup = $('movies > div:nth-child(3) > div').$$('movie-card').$$('h4 > a');
            await browser.get('/');
        let firstMovieName = await movieCardTitles.get(0).getText();
            await browser.sleep(1000);
            await searchField.sendKeys(firstMovieName);
            await goButton.click();
            await browser.sleep(1000);
        let searchResults : any = await searchResultGroup;
        await searchResults.forEach(searchResults => expect(searchResults.getText()).toContain(firstMovieName))
    });

Test is working, but search result is always 1 movie, because of 
```await searchField.sendKeys(firstMovieName);```

The point of this test was to enter search request, that will show several results, for example: 
- try to enter word "fear" in search field, and check if all search results contain this word "fear" in movie name.

**Comment by ssos1** [comment]
Good catch)
Fixed
